name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Use a dedicated PAT secret to allow pushing from the workflow.
          # Create a repo secret named GH_PAGES_PAT with a personal access token (repo scope).
          github_token: ${{ secrets.GH_PAGES_PAT }}
          publish_dir: ./dist
          # The action will create/update the gh-pages branch and set it as the Pages source.
